name: Commit Catalog
on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - '**/README.md'
jobs:
  commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Validate JSON and create catalog
      run: python createCatalog.py
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f catalog.json
        git commit -m "Update catalog.json" -a
        git push https://${{secrets.GH_PAT}}@github.com/${{github.repository}}.git HEAD:main
